# Generated by Django 5.2.17 on 2026-09-10 20:17

import agni.identity.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Principal",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("login_key", models.CharField(max_length=200, unique=True)),
                ("external_issuer", models.CharField(blank=True, max_length=200, null=True)),
                ("external_subject", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("APPLICANT", "Applicant"),
                            ("STAFF", "Staff"),
                            ("SERVICE", "Service"),
                        ],
                        max_length=12,
                    ),
                ),
                ("display_name", models.CharField(max_length=160)),
                ("verified_contact_ref", models.UUIDField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("authz_epoch", models.BigIntegerField(default=1)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            managers=[
                ("objects", agni.identity.models.PrincipalManager()),
            ],
        ),
        migrations.CreateModel(
            name="PrincipalFence",
            fields=[
                (
                    "principal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="fence",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="principal",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("external_issuer__isnull", False), ("external_subject__isnull", False)
                ),
                fields=("external_issuer", "external_subject"),
                name="uniq_principal_external_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="principal",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["APPLICANT", "STAFF", "SERVICE"])),
                name="chk_principal_kind",
            ),
        ),
    ]
