# Generated by Django 5.2.17 on 2026-09-10 20:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0001_initial"),
        ("policies", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="principal",
            name="version",
            field=models.BigIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="AccessRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                ("intended_issuer", models.CharField(blank=True, default="", max_length=200)),
                ("intended_subject", models.CharField(blank=True, default="", max_length=200)),
                ("intended_display_name", models.CharField(blank=True, default="", max_length=160)),
                ("requested_role", models.CharField(blank=True, default="", max_length=40)),
                ("requested_capabilities", models.JSONField(blank=True, default=list)),
                ("justification", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("APPROVED", "Approved"),
                            ("DENIED", "Denied"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                ("decision_at", models.DateTimeField(blank=True, null=True)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "beneficiary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jurisdiction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="policies.jurisdiction",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="policies.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuthorityGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                (
                    "capability",
                    models.CharField(
                        choices=[
                            ("case.decide", "case.decide"),
                            ("certificate.status", "certificate.status"),
                            ("policy.approve", "policy.approve"),
                            ("grant.approve", "grant.approve"),
                            ("staff.provision", "staff.provision"),
                            ("export.sensitive", "export.sensitive"),
                            ("notice.publish", "notice.publish"),
                        ],
                        max_length=80,
                    ),
                ),
                (
                    "scope_kind",
                    models.CharField(
                        choices=[
                            ("GLOBAL", "GLOBAL"),
                            ("JURISDICTION", "JURISDICTION"),
                            ("SERVICE", "SERVICE"),
                        ],
                        max_length=12,
                    ),
                ),
                ("category_keys", models.JSONField(blank=True, default=list)),
                ("effective_from", models.DateTimeField()),
                ("effective_until", models.DateTimeField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("APPROVED", "Approved"),
                            ("REVOKED", "Revoked"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PROPOSED",
                        max_length=10,
                    ),
                ),
                ("approval_basis", models.TextField(blank=True, default="")),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jurisdiction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="policies.jurisdiction",
                    ),
                ),
                (
                    "preparer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="policies.service",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authority_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "channel",
                    models.CharField(choices=[("EMAIL", "Email"), ("SMS", "Sms")], max_length=5),
                ),
                ("ciphertext", models.BinaryField()),
                ("lookup_hmac", models.CharField(max_length=64)),
                ("key_version", models.CharField(default="v1", max_length=30)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("replaced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OtpChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("contact_lookup_hmac", models.CharField(max_length=64)),
                (
                    "channel",
                    models.CharField(choices=[("EMAIL", "Email"), ("SMS", "Sms")], max_length=5),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[("SIGN_IN", "Sign In"), ("CONTACT_CHANGE", "Contact Change")],
                        max_length=40,
                    ),
                ),
                ("code_mac", models.CharField(max_length=64)),
                ("pepper_version", models.CharField(max_length=30)),
                ("expires_at", models.DateTimeField()),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                ("delivery_job_id", models.UUIDField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "principal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoleBinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                (
                    "role_key",
                    models.CharField(
                        choices=[
                            ("OFFICER", "OFFICER"),
                            ("SUPERVISOR", "SUPERVISOR"),
                            ("LEADERSHIP", "LEADERSHIP"),
                            ("ADMIN", "ADMIN"),
                            ("POLICY_APPROVER", "POLICY_APPROVER"),
                        ],
                        max_length=40,
                    ),
                ),
                ("effective_from", models.DateTimeField()),
                ("effective_until", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "approved_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.accessrequest",
                    ),
                ),
                (
                    "jurisdiction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="policies.jurisdiction",
                    ),
                ),
                (
                    "principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="role_bindings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="policies.service",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="accessrequest",
            index=models.Index(fields=["status", "created_at"], name="idx_access_request_status"),
        ),
        migrations.AddConstraint(
            model_name="accessrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("approver", models.F("requester")), _negated=True),
                name="chk_access_request_no_self_approval",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["OPEN", "APPROVED", "DENIED", "EXPIRED"])),
                name="chk_access_request_status",
            ),
        ),
        migrations.AddIndex(
            model_name="authoritygrant",
            index=models.Index(
                fields=["subject", "capability", "state"], name="idx_grant_subject_capability"
            ),
        ),
        migrations.AddConstraint(
            model_name="authoritygrant",
            constraint=models.CheckConstraint(
                condition=models.Q(("approver", models.F("preparer")), _negated=True),
                name="chk_grant_approver_not_preparer",
            ),
        ),
        migrations.AddConstraint(
            model_name="authoritygrant",
            constraint=models.CheckConstraint(
                condition=models.Q(("approver", models.F("subject")), _negated=True),
                name="chk_grant_approver_not_subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="authoritygrant",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ["PROPOSED", "APPROVED", "REVOKED", "EXPIRED"])),
                name="chk_grant_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="authoritygrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_until__isnull", True),
                    ("effective_until__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="chk_grant_interval",
            ),
        ),
        migrations.AddConstraint(
            model_name="authoritygrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("scope_kind", "GLOBAL"),
                        ("jurisdiction__isnull", True),
                        ("service__isnull", True),
                    ),
                    models.Q(("scope_kind", "JURISDICTION"), ("jurisdiction__isnull", False)),
                    models.Q(("scope_kind", "SERVICE"), ("service__isnull", False)),
                    _connector="OR",
                ),
                name="chk_grant_scope_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="contactidentity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("replaced_at__isnull", True)),
                fields=("channel", "lookup_hmac"),
                name="uniq_active_contact_lookup",
            ),
        ),
        migrations.AddIndex(
            model_name="otpchallenge",
            index=models.Index(
                fields=["contact_lookup_hmac", "purpose", "created_at"], name="idx_otp_contact"
            ),
        ),
        migrations.AddIndex(
            model_name="otpchallenge",
            index=models.Index(fields=["expires_at"], name="idx_otp_expiry"),
        ),
        migrations.AddIndex(
            model_name="rolebinding",
            index=models.Index(fields=["principal", "role_key"], name="idx_role_binding_principal"),
        ),
        migrations.AddConstraint(
            model_name="rolebinding",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "role_key__in",
                        ["OFFICER", "SUPERVISOR", "LEADERSHIP", "ADMIN", "POLICY_APPROVER"],
                    )
                ),
                name="chk_role_binding_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="rolebinding",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_until__isnull", True),
                    ("effective_until__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="chk_role_binding_interval",
            ),
        ),
    ]
