# Generated by Django 5.2.17 on 2026-09-10 22:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0002_initial"),
        ("identity", "0002_principal_version_accessrequest_authoritygrant_and_more"),
        ("policies", "0003_service_public_summary_policyartifact_policyversion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authoritygrant",
            name="capability",
            field=models.CharField(
                choices=[
                    ("case.decide", "case.decide"),
                    ("certificate.status", "certificate.status"),
                    ("policy.approve", "policy.approve"),
                    ("policy.activate", "policy.activate"),
                    ("grant.approve", "grant.approve"),
                    ("staff.provision", "staff.provision"),
                    ("export.sensitive", "export.sensitive"),
                    ("notice.publish", "notice.publish"),
                ],
                max_length=80,
            ),
        ),
        migrations.CreateModel(
            name="Delegation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                ("capabilities", models.JSONField(default=list)),
                ("effective_from", models.DateTimeField()),
                ("effective_until", models.DateTimeField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("ACTIVE", "Active"),
                            ("REVOKED", "Revoked"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PROPOSED",
                        max_length=10,
                    ),
                ),
                ("evidence_document_id", models.UUIDField(blank=True, null=True)),
                ("reason", models.TextField()),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delegations_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delegate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delegations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "premises",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delegations",
                        to="cases.premises",
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="policies.service",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["delegate", "state"], name="idx_delegation_delegate"),
                    models.Index(
                        fields=["beneficiary", "state"], name="idx_delegation_beneficiary"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("beneficiary", models.F("delegate")), _negated=True),
                        name="chk_delegation_distinct_parties",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("effective_until__gt", models.F("effective_from"))),
                        name="chk_delegation_interval",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("state__in", ["PROPOSED", "ACTIVE", "REVOKED", "EXPIRED"])
                        ),
                        name="chk_delegation_state",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("premises__isnull", False), ("service__isnull", False), _connector="OR"
                        ),
                        name="chk_delegation_has_scope",
                    ),
                ],
            },
        ),
    ]
