# Generated by Django 5.2.17 on 2026-09-11 03:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cases", "0004_submissionrevision_submissiondocument_and_more"),
        ("documents", "0001_initial"),
        ("inspections", "0002_reports"),
        ("obligations", "0001_initial"),
        ("policies", "0003_service_public_summary_policyartifact_policyversion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                ("checklist_item_code", models.CharField(max_length=40)),
                (
                    "severity",
                    models.CharField(
                        choices=[("MANDATORY", "Mandatory"), ("ADVISORY", "Advisory")],
                        max_length=10,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("RESPONSE_RECEIVED", "Response Received"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("VERIFIED_CLOSED", "Verified Closed"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("reinspection_required", models.BooleanField(default=False)),
                ("last_review_reason", models.TextField(blank=True, default="")),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("closure_evidence", models.JSONField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="findings",
                        to="cases.application",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "originating_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="findings",
                        to="inspections.inspectionreport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                ("round_number", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[("INFORMATION", "Information"), ("DEFICIENCY", "Deficiency")],
                        max_length=12,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PUBLISHED", "Published"),
                            ("SATISFIED", "Satisfied"),
                            ("SUPERSEDED", "Superseded"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PUBLISHED",
                        max_length=12,
                    ),
                ),
                ("published_at", models.DateTimeField()),
                ("public_reason", models.TextField()),
                ("internal_note", models.TextField(blank=True, default="")),
                ("response_budget_minutes", models.PositiveIntegerField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notices",
                        to="cases.application",
                    ),
                ),
                (
                    "due_obligation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="obligations.obligation",
                    ),
                ),
                (
                    "policy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="policies.policyversion",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="notices.notice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NoticeItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                ("code", models.CharField(max_length=60)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("required", models.BooleanField(default=True)),
                ("acceptable_evidence_types", models.JSONField(default=list)),
                ("public_guidance", models.TextField(blank=True, default="")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("RESPONSE_RECEIVED", "Response Received"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("ACCEPTED", "Accepted"),
                            ("RETURNED", "Returned"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("reviewer_feedback", models.TextField(blank=True, default="")),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "finding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notice_items",
                        to="notices.finding",
                    ),
                ),
                (
                    "notice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="notices.notice",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResponseRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("number", models.PositiveIntegerField()),
                ("explanation", models.TextField()),
                ("declaration_accepted", models.BooleanField(default=False)),
                ("accepted_at", models.DateTimeField()),
                ("sha256", models.CharField(max_length=64)),
                (
                    "notice_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="notices.noticeitem",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResponseDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "document_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="documents.documentversion",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="notices.responserevision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NoticeItemReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[("ACCEPTED", "Accepted"), ("RETURNED", "Returned")], max_length=10
                    ),
                ),
                ("reason", models.TextField()),
                ("evidence_refs", models.JSONField(default=list)),
                ("accepted_at", models.DateTimeField()),
                (
                    "notice_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="notices.noticeitem",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "response_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="notices.responserevision",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="noticeitem",
            name="current_response",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="notices.responserevision",
            ),
        ),
        migrations.CreateModel(
            name="FindingReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("VERIFIED_CLOSED", "Verified Closed"),
                            ("RETURNED", "Returned"),
                            ("REINSPECTION_REQUIRED", "Reinspection Required"),
                        ],
                        max_length=24,
                    ),
                ),
                ("reason", models.TextField()),
                ("evidence_snapshot", models.JSONField(default=dict)),
                ("accepted_at", models.DateTimeField()),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="notices.finding",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "response_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="notices.responserevision",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="finding",
            name="current_response",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="notices.responserevision",
            ),
        ),
        migrations.AddIndex(
            model_name="notice",
            index=models.Index(fields=["application", "state"], name="idx_notice_case_state"),
        ),
        migrations.AddConstraint(
            model_name="notice",
            constraint=models.UniqueConstraint(
                fields=("application", "type", "round_number"), name="uniq_notice_round"
            ),
        ),
        migrations.AddConstraint(
            model_name="notice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("state__in", ["DRAFT", "PUBLISHED", "SATISFIED", "SUPERSEDED", "CANCELLED"])
                ),
                name="chk_notice_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="responserevision",
            constraint=models.UniqueConstraint(
                fields=("notice_item", "number"), name="uniq_response_revision_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="responsedocument",
            constraint=models.UniqueConstraint(
                fields=("response", "document_version"), name="uniq_response_document"
            ),
        ),
        migrations.AddConstraint(
            model_name="noticeitem",
            constraint=models.UniqueConstraint(
                fields=("notice", "code"), name="uniq_notice_item_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="noticeitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        ["OPEN", "RESPONSE_RECEIVED", "UNDER_REVIEW", "ACCEPTED", "RETURNED"],
                    )
                ),
                name="chk_notice_item_state",
            ),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(fields=["application", "state"], name="idx_finding_case_state"),
        ),
        migrations.AddConstraint(
            model_name="finding",
            constraint=models.UniqueConstraint(
                fields=("originating_report", "checklist_item_code"),
                name="uniq_finding_report_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="finding",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state", "VERIFIED_CLOSED"), _negated=True),
                    models.Q(("closed_at__isnull", False), ("closed_by__isnull", False)),
                    _connector="OR",
                ),
                name="chk_finding_closure_attributed",
            ),
        ),
    ]
