# Generated by Django 5.2.17 on 2026-09-10 20:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                ("key", models.CharField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("DEMO", "Demo"),
                            ("STANDALONE", "Standalone"),
                            ("INTEGRATED_MONITORING", "Integrated Monitoring"),
                        ],
                        default="DEMO",
                        max_length=24,
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("activation_epoch", models.BigIntegerField(default=1)),
                ("system_of_record", models.CharField(default="agni-setu", max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="Jurisdiction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                ("code", models.CharField(max_length=40, unique=True)),
                ("display_name", models.CharField(max_length=160)),
                (
                    "state",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("RETIRED", "Retired")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="policies.jurisdiction",
                    ),
                ),
            ],
        ),
    ]
