# Generated by Django 5.2.17 on 2026-09-10 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("policies", "0001_initial"),
        ("routing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="owner_queue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_services",
                to="routing.dutyqueue",
            ),
        ),
        migrations.AddConstraint(
            model_name="jurisdiction",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ["ACTIVE", "RETIRED"])),
                name="chk_jurisdiction_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="jurisdiction",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent", models.F("id")), _negated=True),
                name="chk_jurisdiction_not_own_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.CheckConstraint(
                condition=models.Q(("mode__in", ["DEMO", "STANDALONE", "INTEGRATED_MONITORING"])),
                name="chk_service_mode",
            ),
        ),
    ]
