# Generated by Django 5.2.17 on 2026-09-10 22:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="public_summary",
            field=models.CharField(blank=True, default="", max_length=400),
        ),
        migrations.CreateModel(
            name="PolicyArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("FORM", "Form"),
                            ("CHECKLIST", "Checklist"),
                            ("CALENDAR", "Calendar"),
                            ("ROUTING", "Routing"),
                            ("TEMPLATE", "Template"),
                        ],
                        max_length=10,
                    ),
                ),
                ("key", models.CharField(max_length=80)),
                ("number", models.PositiveIntegerField()),
                ("schema_version", models.CharField(max_length=20)),
                ("payload", models.JSONField()),
                ("sha256", models.CharField(max_length=64)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "key", "number"), name="uniq_policy_artifact"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("kind__in", ["FORM", "CHECKLIST", "CALENDAR", "ROUTING", "TEMPLATE"])
                        ),
                        name="chk_artifact_kind",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PolicyVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                ("number", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_REVIEW", "In Review"),
                            ("RETURNED", "Returned"),
                            ("APPROVED", "Approved"),
                            ("SCHEDULED", "Scheduled"),
                            ("ACTIVE", "Active"),
                            ("RETIRED", "Retired"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("payload", models.JSONField()),
                ("payload_sha256", models.CharField(max_length=64)),
                ("schema_version", models.CharField(max_length=20)),
                ("effective_from", models.DateTimeField(blank=True, null=True)),
                ("effective_until", models.DateTimeField(blank=True, null=True)),
                ("legal_basis", models.TextField(blank=True, null=True)),
                ("source_references", models.JSONField(blank=True, default=list)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approval_basis", models.TextField(blank=True, default="")),
                (
                    "review_candidate_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("returned_reason", models.TextField(blank=True, default="")),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jurisdiction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policy_versions",
                        to="policies.jurisdiction",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policy_versions",
                        to="policies.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PolicySimulation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("candidate_sha256", models.CharField(max_length=64)),
                ("fixture_suite_key", models.CharField(max_length=80)),
                ("fixture_suite_version", models.CharField(max_length=20)),
                ("engine_version", models.CharField(max_length=20)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField()),
                ("passed", models.BooleanField()),
                ("result_json", models.JSONField()),
                ("correlation_id", models.UUIDField()),
                (
                    "initiated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="simulations",
                        to="policies.policyversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PolicyContributor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("CREATE", "Create"), ("EDIT", "Edit")], max_length=6
                    ),
                ),
                ("command_id", models.UUIDField()),
                (
                    "principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contributors",
                        to="policies.policyversion",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="policyversion",
            index=models.Index(
                fields=["service", "state", "effective_from"], name="idx_policy_service_state"
            ),
        ),
        migrations.AddConstraint(
            model_name="policyversion",
            constraint=models.UniqueConstraint(
                fields=("service", "number"), name="uniq_policy_version_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="policyversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        [
                            "DRAFT",
                            "IN_REVIEW",
                            "RETURNED",
                            "APPROVED",
                            "SCHEDULED",
                            "ACTIVE",
                            "RETIRED",
                        ],
                    )
                ),
                name="chk_policy_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="policyversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("approved_by", models.F("prepared_by")), _negated=True),
                name="chk_policy_approver_not_preparer",
            ),
        ),
        migrations.AddConstraint(
            model_name="policyversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_until__isnull", True),
                    ("effective_from__isnull", True),
                    ("effective_until__gt", models.F("effective_from")),
                    _connector="OR",
                ),
                name="chk_policy_interval",
            ),
        ),
        migrations.AddConstraint(
            model_name="policyversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("state__in", ["APPROVED", "SCHEDULED", "ACTIVE"]), _negated=True),
                    models.Q(("approved_by__isnull", False), ("effective_from__isnull", False)),
                    _connector="OR",
                ),
                name="chk_policy_effective_requires_approval",
            ),
        ),
        migrations.AddIndex(
            model_name="policysimulation",
            index=models.Index(
                fields=["policy_version", "candidate_sha256", "completed_at"],
                name="idx_policy_sim_candidate",
            ),
        ),
        migrations.AddConstraint(
            model_name="policycontributor",
            constraint=models.UniqueConstraint(
                fields=("policy_version", "principal", "command_id"),
                name="uniq_policy_contribution",
            ),
        ),
    ]
