# Generated by Django 5.2.17 on 2026-09-11 20:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("CASES", "Cases"),
                            ("CERTIFICATES", "Certificates"),
                            ("AUDIT", "Audit"),
                            ("REPORT", "Report"),
                        ],
                        max_length=16,
                    ),
                ),
                ("field_set_key", models.CharField(max_length=60)),
                ("purpose", models.CharField(max_length=500)),
                ("scope_snapshot", models.JSONField(default=dict)),
                ("filter_snapshot", models.JSONField(default=dict)),
                ("as_of", models.DateTimeField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("RUNNING", "Running"),
                            ("COMPLETE", "Complete"),
                            ("FAILED", "Failed"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="READY",
                        max_length=10,
                    ),
                ),
                ("row_count", models.BigIntegerField(blank=True, null=True)),
                ("artifact_object_key", models.TextField(blank=True, null=True)),
                ("artifact_sha256", models.CharField(blank=True, max_length=64, null=True)),
                ("artifact_size", models.BigIntegerField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("definition_version", models.CharField(max_length=40)),
                ("logical_action_id", models.UUIDField(unique=True)),
                ("last_error_code", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["requester", "created_at"], name="idx_export_requester")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("kind__in", ["CASES", "CERTIFICATES", "AUDIT", "REPORT"])
                        ),
                        name="chk_export_kind",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("state__in", ["READY", "RUNNING", "COMPLETE", "FAILED", "EXPIRED"])
                        ),
                        name="chk_export_state",
                    ),
                ],
            },
        ),
    ]
