# Generated by Django 5.2.17 on 2026-09-10 20:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboxMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("logical_action_id", models.UUIDField(unique=True)),
                ("event_type", models.CharField(max_length=100)),
                ("aggregate_type", models.CharField(max_length=60)),
                ("aggregate_id", models.UUIDField()),
                ("payload_version", models.PositiveIntegerField(default=1)),
                ("payload", models.JSONField()),
                ("available_at", models.DateTimeField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DISPATCHED", "Dispatched"),
                            ("COMPLETE", "Complete"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("last_dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("dispatch_attempts", models.PositiveIntegerField(default=0)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["state", "available_at"], name="idx_outbox_due")],
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("entity_type", models.CharField(max_length=60)),
                ("entity_id", models.UUIDField()),
                ("action", models.CharField(max_length=100)),
                ("authority_grant_id", models.UUIDField(blank=True, null=True)),
                ("request_id", models.UUIDField()),
                ("timestamp", models.DateTimeField()),
                ("safe_change_summary", models.JSONField()),
                ("prior_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("hash", models.CharField(max_length=64)),
                ("checkpoint_batch_id", models.UUIDField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id", "timestamp"],
                        name="idx_audit_entity_time",
                    ),
                    models.Index(fields=["request_id"], name="idx_audit_request"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CommandReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("target_type", models.CharField(max_length=60)),
                ("target_id", models.UUIDField()),
                ("command_name", models.CharField(max_length=80)),
                ("key_hash", models.CharField(max_length=64)),
                ("request_sha256", models.CharField(max_length=64)),
                ("result_status", models.PositiveSmallIntegerField()),
                ("result_body", models.JSONField()),
                ("resulting_version", models.BigIntegerField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField()),
                ("retain_until", models.DateTimeField()),
                (
                    "principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["retain_until"], name="idx_receipt_retain_until")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "principal",
                            "target_type",
                            "target_id",
                            "command_name",
                            "key_hash",
                        ),
                        name="uniq_command_receipt_scope_key",
                    )
                ],
            },
        ),
    ]
