# Generated by Django 5.2.17 on 2026-09-10 23:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0001_initial"),
        ("routing", "0002_routingentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogicalJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("logical_action_id", models.UUIDField(unique=True)),
                ("kind", models.CharField(max_length=80)),
                ("aggregate_ref", models.JSONField(default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("RETRY_WAIT", "Retry Wait"),
                            ("COMPLETE", "Complete"),
                            ("DEAD_LETTER", "Dead Letter"),
                            ("RECONCILIATION_REQUIRED", "Reconciliation Required"),
                        ],
                        default="PENDING",
                        max_length=24,
                    ),
                ),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=6)),
                ("lease_owner", models.CharField(blank=True, max_length=120, null=True)),
                ("lease_token", models.BigIntegerField(default=0)),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, max_length=80, null=True)),
                ("disposition", models.CharField(blank=True, max_length=40, null=True)),
                ("provider_id", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner_queue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="routing.dutyqueue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField()),
                ("lease_token", models.BigIntegerField()),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("provider_request_id", models.TextField(blank=True, null=True)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SUCCESS", "Success"),
                            ("RETRYABLE", "Retryable"),
                            ("PERMANENT", "Permanent"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=12,
                        null=True,
                    ),
                ),
                ("safe_error", models.JSONField(default=dict)),
                ("response_digest", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="platform.logicaljob",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="logicaljob",
            index=models.Index(fields=["state", "next_attempt_at"], name="idx_job_due"),
        ),
        migrations.AddIndex(
            model_name="logicaljob",
            index=models.Index(fields=["kind", "state"], name="idx_job_kind_state"),
        ),
        migrations.AddConstraint(
            model_name="logicaljob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        [
                            "PENDING",
                            "RUNNING",
                            "RETRY_WAIT",
                            "COMPLETE",
                            "DEAD_LETTER",
                            "RECONCILIATION_REQUIRED",
                        ],
                    )
                ),
                name="chk_job_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobattempt",
            constraint=models.UniqueConstraint(
                fields=("job", "attempt_number"), name="uniq_job_attempt"
            ),
        ),
    ]
