# Generated by Django 5.2.17 on 2026-09-11 19:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cases", "0005_casehold"),
        ("routing", "0003_routingexception"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("HOW_TO", "How To"),
                            ("TECHNICAL", "Technical"),
                            ("ACCESS", "Access"),
                            ("DATA_CORRECTION", "Data Correction"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=160)),
                ("description", models.TextField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("WAITING_FOR_REQUESTER", "Waiting For Requester"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=24,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("NORMAL", "Normal"), ("URGENT", "Urgent")],
                        default="NORMAL",
                        max_length=8,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_tickets",
                        to="cases.application",
                    ),
                ),
                (
                    "owner_queue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_tickets",
                        to="routing.dutyqueue",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupportMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[("REQUESTER", "Requester"), ("INTERNAL", "Internal")],
                        max_length=10,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("MESSAGE", "Message"), ("STATUS", "Status")],
                        default="MESSAGE",
                        max_length=8,
                    ),
                ),
                ("body", models.TextField()),
                ("document_version_ids", models.JSONField(default=list)),
                ("state_after", models.CharField(blank=True, default="", max_length=24)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages",
                        to="support.supportticket",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(fields=["requester", "created_at"], name="idx_ticket_requester"),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(fields=["owner_queue", "state"], name="idx_ticket_queue_state"),
        ),
        migrations.AddConstraint(
            model_name="supportticket",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        ["OPEN", "IN_PROGRESS", "WAITING_FOR_REQUESTER", "RESOLVED", "CLOSED"],
                    )
                ),
                name="chk_support_ticket_state",
            ),
        ),
        migrations.AddIndex(
            model_name="supportmessage",
            index=models.Index(fields=["ticket", "created_at"], name="idx_ticket_message"),
        ),
    ]
