# Generated by Django 5.2.17 on 2026-09-10 22:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0003_service_public_summary_policyartifact_policyversion_and_more"),
        ("routing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoutingEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("ward_key", models.CharField(max_length=40)),
                ("category_key", models.CharField(blank=True, max_length=40, null=True)),
                ("priority", models.IntegerField(default=0)),
                ("effective_from", models.DateTimeField(blank=True, null=True)),
                ("effective_until", models.DateTimeField(blank=True, null=True)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routing_entries",
                        to="policies.policyartifact",
                    ),
                ),
                (
                    "target_jurisdiction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="policies.jurisdiction",
                    ),
                ),
                (
                    "target_queue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="routing.dutyqueue",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["artifact", "ward_key", "category_key"], name="idx_routing_lookup"
                    )
                ],
            },
        ),
    ]
