# Generated by Django 5.2.17 on 2026-09-11 00:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0004_submissionrevision_submissiondocument_and_more"),
        ("policies", "0003_service_public_summary_policyartifact_policyversion_and_more"),
        ("routing", "0002_routingentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoutingException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("NO_MATCH", "No Match"),
                            ("MULTIPLE_MATCH", "Multiple Match"),
                            ("INACTIVE_TARGET", "Inactive Target"),
                        ],
                        max_length=16,
                    ),
                ),
                ("input_snapshot", models.JSONField(default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("RESOLVED", "Resolved")],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                ("resolution", models.TextField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="routing_exceptions",
                        to="cases.application",
                    ),
                ),
                (
                    "owner_queue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="routing.dutyqueue",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "routing_artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="policies.policyartifact",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("state", "OPEN")),
                        fields=("application", "code"),
                        name="uniq_open_routing_exception_per_case_code",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("code__in", ["NO_MATCH", "MULTIPLE_MATCH", "INACTIVE_TARGET"])
                        ),
                        name="chk_routing_exception_code",
                    ),
                ],
            },
        ),
    ]
