# Generated by Django 5.2.17 on 2026-09-11 13:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inspections", "0002_reports"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportConflict",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                ("operation_id", models.UUIDField()),
                ("application_version_seen", models.BigIntegerField()),
                ("local_manifest", models.JSONField(default=dict)),
                ("local_manifest_sha256", models.CharField(max_length=64)),
                ("safe_local_summary", models.TextField()),
                ("reason", models.TextField()),
                ("server_snapshot", models.JSONField(default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("RESOLVED", "Resolved")],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PROPOSE_NEW_REPORT", "Propose New Report"),
                            ("REINSPECTION_REQUIRED", "Reinspection Required"),
                            ("DECLINE", "Decline"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                ("resolution_reason", models.TextField(blank=True, default="")),
                ("selected_evidence_ids", models.JSONField(default=list)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conflicts",
                        to="inspections.inspection",
                    ),
                ),
                (
                    "proposer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("proposer", "operation_id"), name="uniq_conflict_proposal"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("state__in", ["OPEN", "RESOLVED"])),
                        name="chk_conflict_state",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SyncOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("operation_id", models.UUIDField()),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("SUBMIT_INSPECTION_REPORT", "Submit Inspection Report"),
                            ("RECORD_FAILED_VISIT", "Record Failed Visit"),
                        ],
                        max_length=32,
                    ),
                ),
                ("request_sha256", models.CharField(max_length=64)),
                ("base_version", models.BigIntegerField()),
                ("assignment_version", models.BigIntegerField()),
                ("schema_version", models.CharField(max_length=20)),
                (
                    "state",
                    models.CharField(
                        choices=[("ACCEPTED", "Accepted"), ("CONFLICT", "Conflict")], max_length=10
                    ),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("result", models.JSONField(default=dict)),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sync_operations",
                        to="inspections.inspection",
                    ),
                ),
                (
                    "principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sync_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inspections.inspectionreport",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["inspection", "created_at"], name="idx_sync_inspection")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("principal", "operation_id"), name="uniq_sync_operation_principal"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("state__in", ["ACCEPTED", "CONFLICT"])),
                        name="chk_sync_operation_state",
                    ),
                ],
            },
        ),
    ]
