# Generated by Django 5.2.17 on 2026-09-10 20:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("aggregate_version", models.BigIntegerField()),
                ("ordinal", models.PositiveSmallIntegerField(default=0)),
                ("event_type", models.CharField(max_length=100)),
                ("actor_kind", models.CharField(max_length=30)),
                ("occurred_at", models.DateTimeField()),
                ("payload", models.JSONField(default=dict)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("PUBLIC_CASE", "Public Case"),
                            ("INTERNAL", "Internal"),
                            ("RESTRICTED", "Restricted"),
                        ],
                        default="INTERNAL",
                        max_length=12,
                    ),
                ),
                ("request_id", models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name="Premises",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                ("display_name", models.CharField(max_length=160)),
                ("address_line1", models.CharField(max_length=200)),
                ("address_line2", models.CharField(blank=True, default="", max_length=200)),
                ("locality", models.CharField(max_length=100)),
                ("ward_key", models.CharField(max_length=40)),
                ("postal_code", models.CharField(max_length=6)),
                ("category_key", models.CharField(max_length=40)),
                ("area_sqm", models.DecimalField(decimal_places=2, max_digits=12)),
                ("height_m", models.DecimalField(decimal_places=2, max_digits=7)),
                ("floor_count", models.PositiveIntegerField()),
                ("occupancy_count", models.PositiveIntegerField(blank=True, null=True)),
                ("source_reference", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "premises",
            },
        ),
        migrations.CreateModel(
            name="StageInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "DRAFT"),
                            ("SUBMITTED", "SUBMITTED"),
                            ("SCRUTINY", "SCRUTINY"),
                            ("INFO_REQUIRED", "INFO_REQUIRED"),
                            ("INSPECTION_PENDING", "INSPECTION_PENDING"),
                            ("REVIEW_PENDING", "REVIEW_PENDING"),
                            ("COMPLIANCE_PENDING", "COMPLIANCE_PENDING"),
                            ("APPROVED_PENDING_ISSUE", "APPROVED_PENDING_ISSUE"),
                            ("COMPLETED", "COMPLETED"),
                            ("REJECTED", "REJECTED"),
                            ("WITHDRAWN", "WITHDRAWN"),
                        ],
                        max_length=24,
                    ),
                ),
                ("cycle_number", models.PositiveIntegerField()),
                ("policy_version_id", models.UUIDField(blank=True, null=True)),
                ("entered_at", models.DateTimeField()),
                ("exited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                (
                    "public_reference",
                    models.CharField(blank=True, max_length=40, null=True, unique=True),
                ),
                ("draft_reference", models.CharField(max_length=40, unique=True)),
                ("delegation_id", models.UUIDField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "DRAFT"),
                            ("SUBMITTED", "SUBMITTED"),
                            ("SCRUTINY", "SCRUTINY"),
                            ("INFO_REQUIRED", "INFO_REQUIRED"),
                            ("INSPECTION_PENDING", "INSPECTION_PENDING"),
                            ("REVIEW_PENDING", "REVIEW_PENDING"),
                            ("COMPLIANCE_PENDING", "COMPLIANCE_PENDING"),
                            ("APPROVED_PENDING_ISSUE", "APPROVED_PENDING_ISSUE"),
                            ("COMPLETED", "COMPLETED"),
                            ("REJECTED", "REJECTED"),
                            ("WITHDRAWN", "WITHDRAWN"),
                        ],
                        default="DRAFT",
                        max_length=24,
                    ),
                ),
                ("policy_version_id", models.UUIDField(blank=True, null=True)),
                ("submitted_revision_id", models.UUIDField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("prior_certificate_id", models.UUIDField(blank=True, null=True)),
                ("source_system", models.TextField(blank=True, null=True)),
                ("source_case_id", models.TextField(blank=True, null=True)),
                ("source_version", models.BigIntegerField(blank=True, null=True)),
                (
                    "acting_operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
