# Generated by Django 5.2.17 on 2026-09-10 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cases", "0001_initial"),
        ("platform", "0001_initial"),
        ("policies", "0001_initial"),
        ("routing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="jurisdiction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="policies.jurisdiction",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="owner_queue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="routing.dutyqueue",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="policies.service",
            ),
        ),
        migrations.AddField(
            model_name="caseevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="caseevent",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="cases.application",
            ),
        ),
        migrations.AddField(
            model_name="caseevent",
            name="command_receipt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="platform.commandreceipt",
            ),
        ),
        migrations.AddField(
            model_name="premises",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="premises",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="premises",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="cases.premises",
            ),
        ),
        migrations.AddField(
            model_name="stageinstance",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stage_instances",
                to="cases.application",
            ),
        ),
        migrations.AddField(
            model_name="stageinstance",
            name="entered_event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="+", to="cases.caseevent"
            ),
        ),
        migrations.AddField(
            model_name="stageinstance",
            name="exited_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="cases.caseevent",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="current_stage_instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="cases.stageinstance",
            ),
        ),
        migrations.AddIndex(
            model_name="caseevent",
            index=models.Index(
                fields=["application", "occurred_at", "id"], name="idx_case_event_timeline"
            ),
        ),
        migrations.AddConstraint(
            model_name="caseevent",
            constraint=models.UniqueConstraint(
                fields=("application", "aggregate_version", "ordinal"),
                name="uniq_case_event_version_ordinal",
            ),
        ),
        migrations.AddIndex(
            model_name="premises",
            index=models.Index(fields=["owner", "created_at"], name="idx_premises_owner_created"),
        ),
        migrations.AddConstraint(
            model_name="premises",
            constraint=models.CheckConstraint(
                condition=models.Q(("area_sqm__gte", 0)), name="chk_premises_area_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="premises",
            constraint=models.CheckConstraint(
                condition=models.Q(("height_m__gte", 0)), name="chk_premises_height_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="premises",
            constraint=models.CheckConstraint(
                condition=models.Q(("floor_count__gte", 1)),
                name="chk_premises_floor_count_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="stageinstance",
            constraint=models.UniqueConstraint(
                fields=("application", "cycle_number"), name="uniq_stage_instance_cycle"
            ),
        ),
        migrations.AddConstraint(
            model_name="stageinstance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("exited_at__isnull", True)),
                fields=("application",),
                name="uniq_open_stage_per_case",
            ),
        ),
        migrations.AddConstraint(
            model_name="stageinstance",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        [
                            "DRAFT",
                            "SUBMITTED",
                            "SCRUTINY",
                            "INFO_REQUIRED",
                            "INSPECTION_PENDING",
                            "REVIEW_PENDING",
                            "COMPLIANCE_PENDING",
                            "APPROVED_PENDING_ISSUE",
                            "COMPLETED",
                            "REJECTED",
                            "WITHDRAWN",
                        ],
                    )
                ),
                name="chk_stage_instance_state",
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["applicant", "created_at"], name="idx_application_applicant"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["jurisdiction", "status", "submitted_at"],
                name="idx_application_juris_status",
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["owner_queue", "status"], name="idx_application_queue_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "DRAFT",
                            "SUBMITTED",
                            "SCRUTINY",
                            "INFO_REQUIRED",
                            "INSPECTION_PENDING",
                            "REVIEW_PENDING",
                            "COMPLIANCE_PENDING",
                            "APPROVED_PENDING_ISSUE",
                            "COMPLETED",
                            "REJECTED",
                            "WITHDRAWN",
                        ],
                    )
                ),
                name="chk_application_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("source_case_id__isnull", False), ("source_system__isnull", False)
                ),
                fields=("source_system", "source_case_id"),
                name="uniq_application_source_tuple",
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["DRAFT", "WITHDRAWN"]),
                    ("submitted_at__isnull", False),
                    _connector="OR",
                ),
                name="chk_application_received_has_submitted_at",
            ),
        ),
    ]
