# Generated by Django 5.2.17 on 2026-09-10 23:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0002_initial"),
        ("policies", "0003_service_public_summary_policyartifact_policyversion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("revision_number", models.PositiveIntegerField()),
                ("editable_payload", models.JSONField(default=dict)),
                ("form_schema_ref", models.CharField(blank=True, default="", max_length=120)),
                ("saved_at", models.DateTimeField()),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="draft_revisions",
                        to="cases.application",
                    ),
                ),
                (
                    "form_schema_artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="policies.policyartifact",
                    ),
                ),
                (
                    "saved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="application",
            name="current_draft_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="cases.draftrevision",
            ),
        ),
        migrations.AddConstraint(
            model_name="draftrevision",
            constraint=models.UniqueConstraint(
                fields=("application", "revision_number"), name="uniq_draft_revision_number"
            ),
        ),
    ]
