# Generated by Django 5.2.17 on 2026-09-11 00:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0003_draftrevision_application_current_draft_revision_and_more"),
        ("documents", "0001_initial"),
        ("policies", "0003_service_public_summary_policyartifact_policyversion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("number", models.PositiveIntegerField()),
                ("payload", models.JSONField(default=dict)),
                ("premise_snapshot", models.JSONField(default=dict)),
                ("schema_ref", models.CharField(blank=True, default="", max_length=120)),
                ("declaration_snapshot", models.JSONField(default=list)),
                ("selection_explanation", models.JSONField(default=dict)),
                ("accepted_at", models.DateTimeField()),
                ("sha256", models.CharField(max_length=64)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submission_revisions",
                        to="cases.application",
                    ),
                ),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="policies.policyversion",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubmissionDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("requirement_code", models.CharField(max_length=60)),
                (
                    "document_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="documents.documentversion",
                    ),
                ),
                (
                    "submission_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="cases.submissionrevision",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="submissionrevision",
            constraint=models.UniqueConstraint(
                fields=("application", "number"), name="uniq_submission_revision_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="submissiondocument",
            constraint=models.UniqueConstraint(
                fields=("submission_revision", "requirement_code", "document_version"),
                name="uniq_submission_document",
            ),
        ),
    ]
