# Generated by Django 5.2.17 on 2026-09-11 19:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0004_submissionrevision_submissiondocument_and_more"),
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseHold",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ADMINISTRATIVE", "Administrative"),
                            ("COURT_ORDER", "Court Order"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reason", models.TextField()),
                ("authority_grant_id", models.UUIDField(blank=True, null=True)),
                ("starts_at", models.DateTimeField()),
                ("requested_end_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("affected_obligations", models.JSONField(default=list)),
                ("command_block_scope", models.JSONField(default=list)),
                (
                    "state",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("RELEASED", "Released")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("release_reason", models.TextField(blank=True, default="")),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="holds",
                        to="cases.application",
                    ),
                ),
                (
                    "authorized_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "basis_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="documents.documentversion",
                    ),
                ),
                (
                    "released_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["application", "state"], name="idx_case_hold_state")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["ADMINISTRATIVE", "COURT_ORDER"])),
                        name="chk_case_hold_kind",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("state__in", ["ACTIVE", "RELEASED"])),
                        name="chk_case_hold_state",
                    ),
                ],
            },
        ),
    ]
