# Generated by Django 5.2.17 on 2026-09-11 00:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cases", "0004_submissionrevision_submissiondocument_and_more"),
        ("policies", "0003_service_public_summary_policyartifact_policyversion_and_more"),
        ("routing", "0002_routingentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Obligation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                ("certificate_id", models.UUIDField(blank=True, null=True)),
                ("certificate_lifecycle_instance_id", models.UUIDField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("CASE_TARGET", "Case Target"),
                            ("SCRUTINY_TASK", "Scrutiny Task"),
                            ("APPLICANT_RESPONSE", "Applicant Response"),
                            ("INSPECTION_TASK", "Inspection Task"),
                            ("REVIEW_TASK", "Review Task"),
                            ("ISSUANCE_TASK", "Issuance Task"),
                        ],
                        max_length=60,
                    ),
                ),
                (
                    "time_basis",
                    models.CharField(
                        choices=[("CALENDAR", "Calendar"), ("WORKING", "Working")], max_length=10
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("budget_minutes", models.BigIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("SATISFIED", "Satisfied"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("next_action_at", models.DateTimeField(blank=True, null=True)),
                ("generation", models.PositiveIntegerField(default=1)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="obligations",
                        to="cases.application",
                    ),
                ),
                (
                    "application_stage_instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="obligations",
                        to="cases.stageinstance",
                    ),
                ),
                (
                    "calendar_artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="policies.policyartifact",
                    ),
                ),
                (
                    "owner_queue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="obligations",
                        to="routing.dutyqueue",
                    ),
                ),
                (
                    "policy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="policies.policyversion",
                    ),
                ),
                (
                    "responsible_principal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "satisfied_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="cases.caseevent",
                    ),
                ),
                (
                    "start_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="cases.caseevent",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        condition=models.Q(("state", "ACTIVE")),
                        fields=["due_at"],
                        name="idx_obligation_active_due",
                    ),
                    models.Index(
                        fields=["owner_queue", "state"], name="idx_obligation_queue_state"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("budget_minutes__gt", 0)),
                        name="chk_obligation_budget_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("application_stage_instance__isnull", False),
                                ("certificate_lifecycle_instance_id__isnull", True),
                            ),
                            models.Q(
                                ("application_stage_instance__isnull", True),
                                ("certificate_lifecycle_instance_id__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="chk_obligation_exactly_one_instance",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("state__in", ["ACTIVE", "PAUSED", "SATISFIED", "CANCELLED"])
                        ),
                        name="chk_obligation_state",
                    ),
                    models.UniqueConstraint(
                        fields=("application_stage_instance", "kind", "generation"),
                        name="uniq_obligation_stage_kind_generation",
                    ),
                ],
            },
        ),
    ]
