# Generated by Django 5.2.17 on 2026-09-11 11:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("obligations", "0001_initial"),
        ("routing", "0003_routingexception"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ThresholdAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                ("stage_instance_id", models.UUIDField()),
                ("threshold_key", models.CharField(max_length=80)),
                ("scheduled_for", models.DateTimeField()),
                (
                    "action_type",
                    models.CharField(
                        choices=[("REMINDER", "Reminder"), ("ESCALATION", "Escalation")],
                        max_length=12,
                    ),
                ),
                ("level", models.PositiveIntegerField(default=0)),
                ("logical_job_id", models.UUIDField(blank=True, null=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("disposition", models.CharField(blank=True, default="", max_length=40)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="threshold_actions",
                        to="obligations.obligation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Escalation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                ("manual_request_id", models.UUIDField(blank=True, null=True, unique=True)),
                ("level", models.PositiveIntegerField(default=1)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="OPEN",
                        max_length=14,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("next_action", models.TextField(blank=True, default="")),
                ("resolved_event_id", models.UUIDField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escalations",
                        to="obligations.obligation",
                    ),
                ),
                (
                    "owner_queue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escalations",
                        to="routing.dutyqueue",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "threshold_action",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escalation",
                        to="obligations.thresholdaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ObligationPause",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                ("hold_id", models.UUIDField(blank=True, null=True)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("reason_code", models.CharField(max_length=60)),
                ("reason", models.TextField(blank=True, default="")),
                ("authority_grant_id", models.UUIDField(blank=True, null=True)),
                (
                    "authorized_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pauses",
                        to="obligations.obligation",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["obligation", "starts_at"], name="idx_pause_obligation")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ends_at__isnull", True),
                            ("ends_at__gt", models.F("starts_at")),
                            _connector="OR",
                        ),
                        name="chk_pause_interval",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="thresholdaction",
            index=models.Index(fields=["scheduled_for"], name="idx_threshold_scheduled"),
        ),
        migrations.AddConstraint(
            model_name="thresholdaction",
            constraint=models.UniqueConstraint(
                fields=("obligation", "stage_instance_id", "threshold_key"),
                name="uniq_threshold_action",
            ),
        ),
        migrations.AddIndex(
            model_name="escalation",
            index=models.Index(fields=["owner_queue", "state"], name="idx_escalation_queue_state"),
        ),
        migrations.AddConstraint(
            model_name="escalation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("threshold_action__isnull", False),
                    ("manual_request_id__isnull", False),
                    _connector="OR",
                ),
                name="chk_escalation_origin",
            ),
        ),
        migrations.AddConstraint(
            model_name="escalation",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ["OPEN", "ACKNOWLEDGED", "RESOLVED"])),
                name="chk_escalation_state",
            ),
        ),
    ]
