# Generated by Django 5.2.17 on 2026-09-10 20:39

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DemoOutboundMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("channel", models.CharField(max_length=5)),
                ("destination_lookup_hmac", models.CharField(max_length=64)),
                ("destination_masked", models.CharField(max_length=160)),
                ("purpose", models.CharField(max_length=40)),
                ("body", models.TextField()),
                ("reference_id", models.UUIDField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["destination_lookup_hmac", "created_at"], name="idx_demo_msg_dest"
                    )
                ],
            },
        ),
    ]
