# Generated by Django 5.2.17 on 2026-09-11 11:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0004_submissionrevision_submissiondocument_and_more"),
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("logical_key", models.CharField(max_length=160)),
                ("template_key", models.CharField(max_length=80)),
                ("template_version", models.PositiveIntegerField(default=1)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CASE", "Case"),
                            ("NOTICE", "Notice"),
                            ("APPOINTMENT", "Appointment"),
                            ("REVIEW", "Review"),
                            ("OBLIGATION", "Obligation"),
                            ("ESCALATION", "Escalation"),
                        ],
                        max_length=12,
                    ),
                ),
                ("mandatory", models.BooleanField(default=False)),
                ("safe_render_context", models.JSONField(default=dict)),
                ("in_app_title", models.CharField(max_length=200)),
                ("in_app_body", models.TextField()),
                ("target_path", models.CharField(blank=True, default="", max_length=300)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="cases.application",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="cases.caseevent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "channel",
                    models.CharField(choices=[("EMAIL", "Email"), ("SMS", "Sms")], max_length=5),
                ),
                ("job_id", models.UUIDField(blank=True, null=True)),
                ("destination_masked", models.CharField(blank=True, default="", max_length=160)),
                ("provider_message_id", models.TextField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("SENDING", "Sending"),
                            ("ACCEPTED_BY_PROVIDER", "Accepted By Provider"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="READY",
                        max_length=24,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("safe_failure_code", models.CharField(blank=True, max_length=80, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="notifications.notification",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                ("locale", models.CharField(default="en", max_length=8)),
                ("optional_channels", models.JSONField(default=list)),
                ("reduced_motion", models.BooleanField(default=False)),
                (
                    "principal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notification_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "created_at"], name="idx_notification_recipient"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                condition=models.Q(("read_at__isnull", True)),
                fields=["recipient"],
                name="idx_notification_unread",
            ),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                fields=("recipient", "logical_key"), name="uniq_notification_recipient_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="deliveryattempt",
            constraint=models.UniqueConstraint(
                fields=("notification", "channel"), name="uniq_delivery_channel"
            ),
        ),
        migrations.AddConstraint(
            model_name="deliveryattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_message_id__isnull", False)),
                fields=("provider_message_id",),
                name="uniq_delivery_provider_message",
            ),
        ),
    ]
