# Generated by Django 5.2.17 on 2026-09-10 23:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cases", "0003_draftrevision_application_current_draft_revision_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                ("requirement_code", models.CharField(max_length=60)),
                ("original_name", models.CharField(max_length=180)),
                ("media_type", models.CharField(max_length=120)),
                ("size_bytes", models.BigIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("object_key", models.TextField()),
                ("object_version_id", models.TextField()),
                (
                    "scan_state",
                    models.CharField(
                        choices=[
                            ("QUARANTINED", "Quarantined"),
                            ("CLEAN", "Clean"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="QUARANTINED",
                        max_length=12,
                    ),
                ),
                ("scan_engine", models.CharField(blank=True, max_length=120, null=True)),
                ("scan_engine_version", models.CharField(blank=True, max_length=120, null=True)),
                ("scanned_at", models.DateTimeField(blank=True, null=True)),
                ("scan_detail", models.CharField(blank=True, default="", max_length=200)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="cases.application",
                    ),
                ),
                (
                    "premises",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="cases.premises",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="documents.documentversion",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UploadReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("APPLICATION_DRAFT", "Application Draft"),
                            ("NOTICE_RESPONSE", "Notice Response"),
                            ("INSPECTION_EVIDENCE", "Inspection Evidence"),
                            ("SUPPORT_ATTACHMENT", "Support Attachment"),
                            ("POLICY_BASIS", "Policy Basis"),
                        ],
                        max_length=24,
                    ),
                ),
                ("target_id", models.UUIDField()),
                ("requirement_code", models.CharField(max_length=60)),
                ("original_name", models.CharField(max_length=180)),
                ("media_type", models.CharField(max_length=120)),
                ("expected_size", models.BigIntegerField()),
                ("expected_sha256", models.CharField(blank=True, max_length=64, null=True)),
                ("object_key", models.TextField(unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("RESERVED", "Reserved"),
                            ("UPLOADED", "Uploaded"),
                            ("COMPLETED", "Completed"),
                            ("EXPIRED", "Expired"),
                            ("ABORTED", "Aborted"),
                        ],
                        default="RESERVED",
                        max_length=12,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("uploaded_size", models.BigIntegerField(blank=True, null=True)),
                ("uploaded_sha256", models.CharField(blank=True, max_length=64, null=True)),
                ("object_version_id", models.TextField(blank=True, null=True)),
                (
                    "document_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="documents.documentversion",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="documentversion",
            name="reservation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="produced_version",
                to="documents.uploadreservation",
            ),
        ),
        migrations.CreateModel(
            name="DocumentAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("PREVIEW", "Preview"),
                            ("DOWNLOAD", "Download"),
                            ("PRINT", "Print"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "mechanism",
                    models.CharField(
                        choices=[("PROXY", "Proxy"), ("SIGNED_URL", "Signed Url")], max_length=12
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("request_id", models.UUIDField()),
                (
                    "principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accesses",
                        to="documents.documentversion",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["document_version", "created_at"], name="idx_doc_access_time"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="uploadreservation",
            index=models.Index(fields=["state", "expires_at"], name="idx_reservation_expiry"),
        ),
        migrations.AddIndex(
            model_name="uploadreservation",
            index=models.Index(fields=["target_type", "target_id"], name="idx_reservation_target"),
        ),
        migrations.AddConstraint(
            model_name="uploadreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("expected_size__gt", 0)), name="chk_reservation_size_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="uploadreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "target_type__in",
                        [
                            "APPLICATION_DRAFT",
                            "NOTICE_RESPONSE",
                            "INSPECTION_EVIDENCE",
                            "SUPPORT_ATTACHMENT",
                            "POLICY_BASIS",
                        ],
                    )
                ),
                name="chk_reservation_target_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="uploadreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("state__in", ["RESERVED", "UPLOADED", "COMPLETED", "EXPIRED", "ABORTED"])
                ),
                name="chk_reservation_state",
            ),
        ),
        migrations.AddIndex(
            model_name="documentversion",
            index=models.Index(
                fields=["application", "requirement_code"], name="idx_document_app_req"
            ),
        ),
        migrations.AddIndex(
            model_name="documentversion",
            index=models.Index(fields=["sha256"], name="idx_document_sha256"),
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("application__isnull", False), ("premises__isnull", False), _connector="OR"
                ),
                name="chk_document_has_owner_aggregate",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("scan_state__in", ["QUARANTINED", "CLEAN", "REJECTED"])),
                name="chk_document_scan_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("size_bytes__gt", 0)), name="chk_document_size_positive"
            ),
        ),
    ]
