# Generated by Django 5.2.17 on 2026-09-11 01:38

import agni.inspections.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.operations
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cases", "0004_submissionrevision_submissiondocument_and_more"),
        ("policies", "0003_service_public_summary_policyartifact_policyversion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # The officer-booking exclusion constraint compares a UUID with `=` inside a GiST index
        # (data model s.5): PostgreSQL needs btree_gist for that operator class.
        django.contrib.postgres.operations.BtreeGistExtension(),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                ("number", models.PositiveIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUPERSEDED", "Superseded"),
                            ("REVOKED", "Revoked"),
                            ("FULFILLED", "Fulfilled"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField()),
                ("booking_start", models.DateTimeField(blank=True, null=True)),
                ("booking_end", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                ("attempt_number", models.PositiveIntegerField()),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("INITIAL", "Initial"),
                            ("REINSPECTION", "Reinspection"),
                            ("CLARIFICATION", "Clarification"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="REQUESTED",
                        max_length=12,
                    ),
                ),
                ("scheduled_start", models.DateTimeField(blank=True, null=True)),
                ("scheduled_end", models.DateTimeField(blank=True, null=True)),
                ("appointment_timezone", models.CharField(blank=True, default="", max_length=64)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("check_in", models.JSONField(blank=True, default=dict)),
                ("failed_reason_code", models.CharField(blank=True, max_length=50, null=True)),
                ("failed_notes", models.TextField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True, null=True)),
                ("request_reason", models.TextField(blank=True, default="")),
                ("preferred_window_start", models.DateTimeField(blank=True, null=True)),
                ("preferred_window_end", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspections",
                        to="cases.application",
                    ),
                ),
                (
                    "checklist_artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="policies.policyartifact",
                    ),
                ),
                (
                    "current_assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inspections.assignment",
                    ),
                ),
                (
                    "parent_inspection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="follow_ups",
                        to="inspections.inspection",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assignment",
            name="inspection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments",
                to="inspections.inspection",
            ),
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                (
                    "kind",
                    models.CharField(
                        choices=[("AVAILABLE", "Available"), ("UNAVAILABLE", "Unavailable")],
                        max_length=12,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("reason_code", models.CharField(max_length=40)),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="availability",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["officer", "starts_at", "ends_at"], name="idx_availability_officer"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                        name="chk_availability_interval",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="inspection",
            index=models.Index(fields=["application", "status"], name="idx_inspection_case_status"),
        ),
        migrations.AddIndex(
            model_name="inspection",
            index=models.Index(fields=["scheduled_start"], name="idx_inspection_scheduled"),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.UniqueConstraint(
                fields=("application", "attempt_number"), name="uniq_inspection_attempt"
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("scheduled_end__isnull", True),
                    ("scheduled_end__gt", models.F("scheduled_start")),
                    _connector="OR",
                ),
                name="chk_inspection_schedule_interval",
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "REQUESTED",
                            "SCHEDULED",
                            "IN_PROGRESS",
                            "COMPLETED",
                            "FAILED",
                            "CANCELLED",
                        ],
                    )
                ),
                name="chk_inspection_status",
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(fields=["officer", "state"], name="idx_assignment_officer_state"),
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.UniqueConstraint(
                fields=("inspection", "number"), name="uniq_assignment_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "ACTIVE")),
                fields=("inspection",),
                name="one_active_assignment_per_inspection",
            ),
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("booking_end__isnull", True),
                    ("booking_end__gt", models.F("booking_start")),
                    _connector="OR",
                ),
                name="chk_assignment_booking_interval",
            ),
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(
                    ("booking_end__isnull", False),
                    ("booking_start__isnull", False),
                    ("state", "ACTIVE"),
                ),
                expressions=[
                    (
                        agni.inspections.models.TsTzRange(
                            "booking_start",
                            "booking_end",
                            django.contrib.postgres.fields.ranges.RangeBoundary(),
                        ),
                        "&&",
                    ),
                    ("officer", "="),
                ],
                name="no_active_officer_booking_overlap",
            ),
        ),
    ]
