# Generated by Django 5.2.17 on 2026-09-11 02:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
        ("inspections", "0001_initial"),
        ("policies", "0003_service_public_summary_policyartifact_policyversion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("revision_number", models.PositiveIntegerField()),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                (
                    "capture_unavailable_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("accepted_at", models.DateTimeField()),
                ("observations", models.JSONField(default=list)),
                ("summary", models.TextField()),
                ("evaluation", models.JSONField(default=dict)),
                ("sha256", models.CharField(max_length=64)),
                ("source_operation_id", models.UUIDField(blank=True, null=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inspections.assignment",
                    ),
                ),
                (
                    "checklist_artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="policies.policyartifact",
                    ),
                ),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="inspections.inspection",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inspections.inspectionreport",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="inspection",
            name="current_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inspections.inspectionreport",
            ),
        ),
        migrations.CreateModel(
            name="ReportEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("item_code", models.CharField(max_length=40)),
                ("capture_metadata", models.JSONField(default=dict)),
                (
                    "document_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="documents.documentversion",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence",
                        to="inspections.inspectionreport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InspectionDraft",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                ("base_inspection_version", models.BigIntegerField()),
                ("assignment_version", models.BigIntegerField()),
                ("payload", models.JSONField(default=dict)),
                ("client_operation_id", models.UUIDField(blank=True, null=True)),
                ("local_revision", models.PositiveIntegerField(blank=True, null=True)),
                ("saved_at", models.DateTimeField()),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drafts",
                        to="inspections.inspection",
                    ),
                ),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("inspection", "officer"), name="uniq_inspection_draft_per_officer"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="inspectionreport",
            constraint=models.UniqueConstraint(
                fields=("inspection", "revision_number"), name="uniq_inspection_report_revision"
            ),
        ),
        migrations.AddConstraint(
            model_name="reportevidence",
            constraint=models.UniqueConstraint(
                fields=("report", "item_code", "document_version"), name="uniq_report_evidence"
            ),
        ),
    ]
