# Generated by Django 5.2.17 on 2026-09-11 15:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cases", "0004_submissionrevision_submissiondocument_and_more"),
        ("identity", "0003_alter_authoritygrant_capability_delegation"),
        ("inspections", "0002_reports"),
        ("policies", "0003_service_public_summary_policyartifact_policyversion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("decision_number", models.PositiveIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[("APPROVE", "Approve"), ("REJECT", "Reject")], max_length=10
                    ),
                ),
                ("evidence_snapshot", models.JSONField(default=dict)),
                ("reason", models.TextField()),
                ("public_reason", models.TextField()),
                ("accepted_at", models.DateTimeField()),
                ("sha256", models.CharField(max_length=64)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="cases.application",
                    ),
                ),
                (
                    "authority_grant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.authoritygrant",
                    ),
                ),
                (
                    "policy_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="policies.policyversion",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inspections.inspectionreport",
                    ),
                ),
                (
                    "submitted_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="cases.submissionrevision",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("application", "decision_number"), name="uniq_decision_number"
                    ),
                    models.UniqueConstraint(
                        fields=("application",), name="uniq_final_decision_per_application"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["APPROVE", "REJECT"])),
                        name="chk_decision_kind",
                    ),
                ],
            },
        ),
    ]
