"""Local developer settings.

Never used in production. Defaults here exist only so that `manage.py check` and local
development work before an env file is generated; they are visibly insecure and rejected by
the production settings module.
"""

from pathlib import Path

import environ

# Optional env files; ignored when absent. Real environment variables always win. They must be
# read BEFORE base.py computes DATABASES and the other env-derived settings.
#   backend/.env       - manual developer override
#   <repo>/.env.local  - generated by scripts/dev/up.sh (gitignored)
_BACKEND_DIR = Path(__file__).resolve().parents[2]
environ.Env.read_env(str(_BACKEND_DIR / ".env"))
environ.Env.read_env(str(_BACKEND_DIR.parent / ".env.local"))

from .base import *  # noqa: E402, F403
from .base import env  # noqa: E402

DEBUG = True
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["127.0.0.1", "localhost"])
SECRET_KEY = env.str(
    "DJANGO_SECRET_KEY",
    default="local-insecure-development-key-do-not-use-outside-localhost",  # noqa: S105
)
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=["http://localhost:5173"])
ENABLE_DEMO_CONTROLS = env.bool("ENABLE_DEMO_CONTROLS", default=True)
