# Generated by Django 5.2.17 on 2026-09-11 15:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cases", "0004_submissionrevision_submissiondocument_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("object_key", models.TextField(unique=True)),
                ("object_version_id", models.TextField()),
                ("sha256", models.CharField(max_length=64)),
                ("size_bytes", models.BigIntegerField()),
                ("media_type", models.CharField(max_length=120)),
                (
                    "mode",
                    models.CharField(
                        choices=[("DEMO_WATERMARK", "Demo Watermark"), ("SIGNED", "Signed")],
                        max_length=20,
                    ),
                ),
                ("renderer", models.CharField(max_length=80)),
                ("renderer_version", models.CharField(max_length=80)),
                ("rendered_at", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CertificateSequence",
            fields=[
                ("year", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("last_number", models.PositiveIntegerField(default=100)),
            ],
            options={
                "db_table": "certificates_certificatesequence",
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                (
                    "outcome_kind",
                    models.CharField(
                        choices=[
                            ("DEMO_CERTIFICATE", "Demo Certificate"),
                            ("ISSUED_DEPARTMENT", "Issued Department"),
                            ("REGISTERED_EXTERNAL", "Registered External"),
                        ],
                        max_length=24,
                    ),
                ),
                ("certificate_number", models.CharField(max_length=50, unique=True)),
                ("verification_token_hash", models.CharField(max_length=64, unique=True)),
                ("verification_token_ciphertext", models.BinaryField()),
                ("token_key_version", models.CharField(max_length=40)),
                ("issuer_reference", models.TextField()),
                ("issued_at", models.DateTimeField()),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                (
                    "recorded_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("REVOKED", "Revoked"),
                            ("SUPERSEDED", "Superseded"),
                        ],
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                ("source_system", models.TextField(blank=True, null=True)),
                ("source_certificate_id", models.TextField(blank=True, null=True)),
                ("verified_source_at", models.DateTimeField(blank=True, null=True)),
                ("is_demo", models.BooleanField(default=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificates",
                        to="cases.application",
                    ),
                ),
                (
                    "predecessor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="successors",
                        to="certificates.certificate",
                    ),
                ),
                (
                    "artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="certificates.certificateartifact",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IssuanceRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                ("logical_action_id", models.UUIDField(unique=True)),
                ("certificate_number", models.CharField(max_length=50, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("READY", "Ready"),
                            ("PROCESSING", "Processing"),
                            ("RECONCILIATION_REQUIRED", "Reconciliation Required"),
                            ("PUBLISHED", "Published"),
                            ("FAILED", "Failed"),
                        ],
                        default="READY",
                        max_length=24,
                    ),
                ),
                ("template_key", models.CharField(max_length=80)),
                ("template_version", models.PositiveIntegerField()),
                ("render_snapshot", models.JSONField(default=dict)),
                ("token_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("token_ciphertext", models.BinaryField(blank=True, null=True)),
                ("token_key_version", models.CharField(blank=True, default="", max_length=40)),
                ("provider_request_id", models.TextField(blank=True, null=True)),
                ("signature_verification", models.JSONField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error_code", models.CharField(blank=True, max_length=80, null=True)),
                ("reconciliation_note", models.TextField(blank=True, default="")),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issuance_requests",
                        to="cases.application",
                    ),
                ),
                (
                    "artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="certificates.certificateartifact",
                    ),
                ),
            ],
        ),
    ]
