# Generated by Django 5.2.17 on 2026-09-11 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("certificates", "0001_initial"),
        ("decisions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuancerequest",
            name="decision",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issuance_request",
                to="decisions.decision",
            ),
        ),
        migrations.AddField(
            model_name="certificateartifact",
            name="issuance_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="artifacts",
                to="certificates.issuancerequest",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="issuance_request",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="certificate",
                to="certificates.issuancerequest",
            ),
        ),
        migrations.AddConstraint(
            model_name="issuancerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        ["READY", "PROCESSING", "RECONCILIATION_REQUIRED", "PUBLISHED", "FAILED"],
                    )
                ),
                name="chk_issuance_state",
            ),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(fields=["application", "issued_at"], name="idx_certificate_case"),
        ),
        migrations.AddConstraint(
            model_name="certificate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_system__isnull", False)),
                fields=("source_system", "source_certificate_id"),
                name="uniq_certificate_external_tuple",
            ),
        ),
        migrations.AddConstraint(
            model_name="certificate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("recorded_status__in", ["ACTIVE", "SUSPENDED", "REVOKED", "SUPERSEDED"])
                ),
                name="chk_certificate_recorded_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="certificate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "outcome_kind__in",
                        ["DEMO_CERTIFICATE", "ISSUED_DEPARTMENT", "REGISTERED_EXTERNAL"],
                    )
                ),
                name="chk_certificate_outcome_kind",
            ),
        ),
    ]
