# Generated by Django 5.2.17 on 2026-09-11 19:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certificates", "0002_initial"),
        ("documents", "0001_initial"),
        ("identity", "0003_alter_authoritygrant_capability_delegation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateStatusInstrument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("SUSPEND", "Suspend"),
                            ("REINSTATE", "Reinstate"),
                            ("REVOKE", "Revoke"),
                            ("SUPERSEDE", "Supersede"),
                        ],
                        max_length=12,
                    ),
                ),
                ("effective_at", models.DateTimeField()),
                ("reason", models.TextField()),
                ("public_reason", models.TextField()),
                (
                    "status_before",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("REVOKED", "Revoked"),
                            ("SUPERSEDED", "Superseded"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "status_after",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("REVOKED", "Revoked"),
                            ("SUPERSEDED", "Superseded"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "authority_grant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="identity.authoritygrant",
                    ),
                ),
                (
                    "certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="status_instruments",
                        to="certificates.certificate",
                    ),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="documents.documentversion",
                    ),
                ),
                (
                    "successor_certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="certificates.certificate",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["certificate", "effective_at"], name="idx_status_instrument_cert"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("action__in", ["SUSPEND", "REINSTATE", "REVOKE", "SUPERSEDE"])
                        ),
                        name="chk_status_instrument_action",
                    )
                ],
            },
        ),
    ]
