# Generated by Django 5.2.17 on 2026-09-11 21:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cases", "0005_casehold"),
        ("routing", "0003_routingexception"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                ("key", models.CharField(max_length=80, unique=True)),
                ("display_name", models.CharField(max_length=160)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("SIMULATED", "Simulated"),
                            ("SANDBOX", "Sandbox"),
                            ("LIVE", "Live"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "provider_kind",
                    models.CharField(
                        choices=[
                            ("partner_case_source", "Partner Case Source"),
                            ("external_certificate_source", "External Certificate Source"),
                            ("message_sender", "Message Sender"),
                            ("certificate_signer", "Certificate Signer"),
                            ("malware_scanner", "Malware Scanner"),
                            ("object_store", "Object Store"),
                            ("staff_identity", "Staff Identity"),
                        ],
                        max_length=60,
                    ),
                ),
                ("system_of_record_fields", models.JSONField(blank=True, default=list)),
                ("endpoint_allowlist", models.JSONField(blank=True, default=list)),
                ("capabilities", models.JSONField(blank=True, default=list)),
                ("credential_secret_ref", models.CharField(blank=True, default="", max_length=200)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DISABLED", "Disabled"),
                            ("ENABLED", "Enabled"),
                            ("DEGRADED", "Degraded"),
                        ],
                        default="DISABLED",
                        max_length=10,
                    ),
                ),
                ("freshness_budget_seconds", models.PositiveIntegerField(default=86400)),
                (
                    "last_health_status",
                    models.CharField(
                        choices=[
                            ("NOT_RUN", "Not Run"),
                            ("OK", "Ok"),
                            ("FAIL", "Fail"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="NOT_RUN",
                        max_length=10,
                    ),
                ),
                ("last_health_at", models.DateTimeField(blank=True, null=True)),
                ("last_health_detail", models.CharField(blank=True, default="", max_length=200)),
                ("last_event_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner_queue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="routing.dutyqueue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntegrationInbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_event_id", models.CharField(max_length=160)),
                ("source_entity_id", models.CharField(max_length=160)),
                ("source_sequence", models.BigIntegerField(blank=True, null=True)),
                ("event_type", models.CharField(max_length=80)),
                ("schema_version", models.CharField(max_length=20)),
                ("occurred_at", models.DateTimeField()),
                ("received_at", models.DateTimeField()),
                ("payload", models.JSONField(default=dict)),
                ("payload_sha256", models.CharField(max_length=64)),
                ("auth_evidence", models.JSONField(default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received"),
                            ("PROCESSED", "Processed"),
                            ("QUARANTINED", "Quarantined"),
                            ("CONFLICT", "Conflict"),
                        ],
                        default="RECEIVED",
                        max_length=12,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("disposition", models.CharField(blank=True, max_length=40, null=True)),
                ("error_code", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inbox",
                        to="integrations.integration",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntegrationConflict",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                ("source_entity_id", models.TextField()),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            ("SEQUENCE_GAP", "Sequence Gap"),
                            ("OLDER_THAN_APPLIED", "Older Than Applied"),
                            ("PAYLOAD_MISMATCH", "Payload Mismatch"),
                            ("SCHEMA_INVALID", "Schema Invalid"),
                        ],
                        max_length=80,
                    ),
                ),
                ("detail", models.JSONField(default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("RESOLVED", "Resolved")],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("APPLY_VERIFIED_SOURCE", "Apply Verified Source"),
                            ("IGNORE_DUPLICATE", "Ignore Duplicate"),
                            ("REQUEST_RESEND", "Request Resend"),
                            ("KEEP_QUARANTINED", "Keep Quarantined"),
                            ("PREDECESSOR_ARRIVED", "Predecessor Arrived"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("resolution_basis", models.JSONField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conflicts",
                        to="integrations.integration",
                    ),
                ),
                (
                    "owner_queue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="routing.dutyqueue",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inbox",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conflicts",
                        to="integrations.integrationinbox",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartnerEntityState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.BigIntegerField(default=1)),
                ("source_entity_id", models.CharField(max_length=160)),
                ("applied_sequence", models.BigIntegerField(blank=True, null=True)),
                (
                    "applied_source_version",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("applied_event_id", models.CharField(blank=True, default="", max_length=160)),
                ("applied_occurred_at", models.DateTimeField(blank=True, null=True)),
                ("snapshot", models.JSONField(default=dict)),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="cases.application",
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entity_states",
                        to="integrations.integration",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="integration",
            constraint=models.CheckConstraint(
                condition=models.Q(("mode__in", ["SIMULATED", "SANDBOX", "LIVE"])),
                name="chk_integration_mode",
            ),
        ),
        migrations.AddConstraint(
            model_name="integration",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ["DISABLED", "ENABLED", "DEGRADED"])),
                name="chk_integration_state",
            ),
        ),
        migrations.AddIndex(
            model_name="integrationinbox",
            index=models.Index(
                fields=["integration", "source_entity_id", "source_sequence"],
                name="idx_inbox_entity_sequence",
            ),
        ),
        migrations.AddIndex(
            model_name="integrationinbox",
            index=models.Index(fields=["integration", "state"], name="idx_inbox_state"),
        ),
        migrations.AddConstraint(
            model_name="integrationinbox",
            constraint=models.UniqueConstraint(
                fields=("integration", "source_event_id"), name="one_partner_event"
            ),
        ),
        migrations.AddConstraint(
            model_name="integrationinbox",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("state__in", ["RECEIVED", "PROCESSED", "QUARANTINED", "CONFLICT"])
                ),
                name="chk_inbox_state",
            ),
        ),
        migrations.AddIndex(
            model_name="integrationconflict",
            index=models.Index(fields=["integration", "state"], name="idx_int_conflict_state"),
        ),
        migrations.AddIndex(
            model_name="integrationconflict",
            index=models.Index(fields=["owner_queue", "state"], name="idx_int_conflict_queue"),
        ),
        migrations.AddConstraint(
            model_name="integrationconflict",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ["OPEN", "RESOLVED"])),
                name="chk_integration_conflict_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="partnerentitystate",
            constraint=models.UniqueConstraint(
                fields=("integration", "source_entity_id"), name="uniq_partner_entity"
            ),
        ),
    ]
